spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    url: jdbc:mysql://106.54.134.159:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 304
  servlet:
    context-path: /sell



#logging:
##  用在服务器中
##  file: /var/log/tomcat/sell/
#
#  level: debug
##  日志的记录层级
##  level:
##    com.sdjzu.sell.LoggerTest: debug
#  pattern:
#    console: "%d - %msg%n"