spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    url: jdbc:mysql://106.54.134.159:3306//sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#server:
#  context-path: /sell

#logging:
##  放在服务器上
##  file: /var/log/tomcat/sell/
#
#  level: debug
##  也可以配置类的级别
##  level:
##    com.sdjzu.sell.LoggerTest: debug
#  pattern:
#    console: "%d - %msg%n"